---
title: Tamil Christian Fellowship, Melbourne
author: TCF
email: tamilchristianfellowshipmelb@gmail.com
description: A vibrant, Tamil, Pentecostal Church in Melbourne, sharing the Gospel
  since May 2015.
baseurl: "/tcfmelb"
url: tcfmelbourne.org/tcfmelb
defaults:
- scope: ''
  values: ''
plugins:
- jekyll-feed
- jekyll-menus
menu:
  main:
    weight: 2
    title: Events
